<a href="https://colab.research.google.com/github/deepakmoud/Signature-Verification/blob/master/SIGNATURE_RECOGNITION%20vgg16.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import  keras
from sklearn.model_selection import  train_test_split

TEST_DIR='/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/TEST1/'

SIGNATURE_CLASSES = ['001', '002', '003','004','006','009','012','013','014','015','016','017','018','019','020','021','022','023','024','025','026','027','028','029','030','031','032','033','034','035','036','037','038','039','040','041','042','043','044','045','046','047','048','049','050','051','052','053','054','055','056','057','058','059','060','061','062','063','064','065','066','067','068','069']

In [0]:
# Updating Keras
pip install -U keras

Requirement already up-to-date: keras in /usr/local/lib/python3.6/dist-packages (2.3.1)


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [0]:
import os, random
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import log_loss
from sklearn.preprocessing import LabelEncoder
import scipy.misc  as mc
import matplotlib.pyplot as plt
from matplotlib import ticker
#import seaborn as sns
#%matplotlib inline 

from keras.models import Sequential
from keras.layers import Dropout, Flatten, Convolution2D, MaxPooling2D, ZeroPadding2D, Dense, Activation
from keras.optimizers import SGD, Adagrad
from keras.callbacks import EarlyStopping
from keras.utils import np_utils
from keras.optimizers import RMSprop, Adam
from keras import backend as K
ROWS = 224  
COLS = 224 
CHANNELS = 3
TRAIN_DIR='/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/train/'
# Importing the Keras libraries and packages
from keras.layers import Input, Flatten, Dense
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Input, Flatten, Dense
from keras.callbacks import Callback, ModelCheckpoint
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
import warnings 
warnings.filterwarnings('ignore')

In [0]:
def root_mean_squared_error(y_true, y_pred):
    """
    RMSE loss function
    """
    return K.sqrt(K.mean(K.square(y_pred - y_true), axis=-1))


In [0]:
def get_images(fish):
    """Load files from train folder"""
    fish_dir = TRAIN_DIR+'{}'.format(fish)
    images = [fish+'/'+im for im in os.listdir(fish_dir)]
    return images

In [0]:
pip install scipy==1.1.0

In [0]:
def read_image(src):
    import os
    from scipy import misc
    filepath=src
    im=misc.imread(filepath)
    import scipy.misc  as mc
     
    return mc.imresize(im,(ROWS,COLS))

In [0]:

import imageio
from skimage.transform import resize
X_all = np.ndarray((len(files), ROWS, COLS, CHANNELS), dtype=np.uint8)
print(X_all.shape)
#im = imageio.imread(files)
#im=resize(im, (ROWS, COLS))
for i, im in enumerate(files):
  im1=imageio.imread(TRAIN_DIR+im)
  print(im1)
 # print('size of input image'+str(im1.shape))
  im1=resize(im1,(ROWS, COLS, CHANNELS))
 # print('resized image'+str(im1.shape))
  X_all[i] = im1
 # print('x_all[]'+str(X_all[i].shape))
  print( X_all[i])
  
 

Streaming output truncated to the last 5000 lines.
  [0 0 0]]]
[[[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [246 251 252]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [242 253 252]]

 ...

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]]
[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ...

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ...
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]

KeyboardInterrupt: ignored

In [0]:
import imageio
from skimage.transform import resize
filepath='/content/drive/My Drive/Signature_Recognition_DeepLearning-master/data/train/Z/021009_000.png'
im = imageio.imread(filepath)
print(im.shape)
im=resize(im, (ROWS, COLS), preserve_range=True)
print(im.shape)

(28, 28, 3)
(28, 28, 3)


In [0]:
files = []
y_all = []
for fish in SIGNATURE_CLASSES:
    fish_files = get_images(fish)
    files.extend(fish_files)
    
    y_fish = np.tile(fish, len(fish_files))
    y_all.extend(y_fish)
    print("{0} photos of {1}".format(len(fish_files), fish))
    
y_all = np.array(y_all)
print(len(files))
print(len(y_all))


24 photos of 001
24 photos of 002
24 photos of 003
24 photos of 004
24 photos of 006
24 photos of 009
24 photos of 012
12 photos of 013
24 photos of 014
24 photos of 015
23 photos of 016
12 photos of 017
12 photos of 018
12 photos of 019
12 photos of 020
12 photos of 021
12 photos of 022
12 photos of 023
12 photos of 024
12 photos of 025
12 photos of 026
12 photos of 027
12 photos of 028
12 photos of 029
12 photos of 030
12 photos of 031
12 photos of 032
12 photos of 033
12 photos of 034
12 photos of 035
12 photos of 036
12 photos of 037
12 photos of 038
12 photos of 039
12 photos of 040
12 photos of 041
12 photos of 042
12 photos of 043
12 photos of 044
12 photos of 045
12 photos of 046
12 photos of 047
12 photos of 048
12 photos of 049
12 photos of 050
12 photos of 051
12 photos of 052
12 photos of 053
12 photos of 054
12 photos of 055
12 photos of 056
12 photos of 057
12 photos of 058
12 photos of 059
12 photos of 060
12 photos of 061
12 photos of 062
12 photos of 063
12 photos of 0

In [0]:
X_all = np.ndarray((len(files), ROWS, COLS, CHANNELS), dtype=np.uint8)
print(X_all.shape)
for i, im in enumerate(files): 
    X_all[i] = read_image(TRAIN_DIR+im)
    print(X_all[i])   
   
    if i%1000 == 0: print('Processed {} of {}'.format(i, len(files)))


print(X_all.shape)

Streaming output truncated to the last 5000 lines.
[[[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 ...

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 253]
  [245 253 253]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]]
[[[244 253 253]
  [244 252 251]
  [244 252 251]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[244 253 253]
  [244 252 251]
  [244 252 251]
  ...
  [245 253 253]
  [245 253 253]
  [245 253 253]]

 [[245 253 253]
  [245 253 252]
  [245 253 252]
  ...
  [245 253 251]
  [245 253 251]
  [245 253 253]]

 ...

 

In [0]:

y_all = LabelEncoder().fit_transform(y_all)
y_all = np_utils.to_categorical(y_all)


In [0]:
from sklearn.model_selection import train_test_split

X_train, X_valid, y_train, y_valid = train_test_split(X_all, y_all, 
                                                    test_size=0.3, random_state=23, 
                                                    stratify=y_all)



optimizer = RMSprop(lr=1e-4)
objective = 'categorical_crossentropy'

In [0]:
def center_normalize(x):
    return (x - K.mean(x)) / K.std(x)
print('1')

1


In [0]:
model = Sequential()

model.add(Activation(activation=center_normalize, input_shape=(ROWS, COLS, CHANNELS)))

model.add(Convolution2D(64, 3, 3, border_mode='same'))
model.add(Activation('relu'))
model.add(Convolution2D(64, 3, 3, border_mode='valid'))
model.add(Activation('relu'))
model.add(ZeroPadding2D(padding=(1, 1)))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Dropout(0.25))

model.add(Convolution2D(96, 3, 3, border_mode='same'))
model.add(Activation('relu'))
model.add(Convolution2D(96, 3, 3, border_mode='valid'))
model.add(Activation('relu'))
model.add(ZeroPadding2D(padding=(1, 1)))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Dropout(0.25))

model.add(Convolution2D(128, 2, 2, border_mode='same'))
model.add(Activation('relu'))
model.add(Convolution2D(128, 2, 2, border_mode='same'))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2, 2), strides=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten())
model.add(Dense(1024))
model.add(Activation('relu'))
model.add(Dropout(0.5))


model.add(Dense(len(SIGNATURE_CLASSES)))
model.add(Activation('softmax'))
 


In [0]:
adam = Adam(lr=0.0001)
model.compile(optimizer=adam, loss=root_mean_squared_error, metrics=['accuracy'])




In [0]:
early_stopping = EarlyStopping(monitor='val_acc', patience=4, verbose=1, mode='auto')        
       
model.fit(X_train, y_train, batch_size=32, nb_epoch=50,
              validation_split=0.1, verbose=1, shuffle=True, callbacks=[early_stopping])

Train on 558 samples, validate on 62 samples
Epoch 1/50
558/558 [==============================] - 3s 6ms/step - loss: 0.1223 - accuracy: 0.0699 - val_loss: 0.1210 - val_accuracy: 0.1935
Epoch 2/50
558/558 [==============================] - 3s 5ms/step - loss: 0.1096 - accuracy: 0.2455 - val_loss: 0.1077 - val_accuracy: 0.2258
Epoch 3/50
558/558 [==============================] - 3s 5ms/step - loss: 0.0954 - accuracy: 0.3548 - val_loss: 0.0979 - val_accuracy: 0.3710
Epoch 4/50
558/558 [==============================] - 3s 6ms/step - loss: 0.0859 - accuracy: 0.4427 - val_loss: 0.0847 - val_accuracy: 0.5000
Epoch 5/50
558/558 [==============================] - 3s 6ms/step - loss: 0.0703 - accuracy: 0.5466 - val_loss: 0.0722 - val_accuracy: 0.6129
Epoch 6/50
558/558 [==============================] - 3s 5ms/step - loss: 0.0604 - accuracy: 0.6290 - val_loss: 0.0708 - val_accuracy: 0.5323
Epoch 7/50
558/558 [==============================] - 3s 5ms/step - loss: 0.0542 - accuracy: 0.6685 - v

In [0]:
preds = model.predict(X_valid, verbose=1)
print("Validation Log Loss: {}".format(log_loss(y_valid, preds)))

267/267 [==============================] - 1s 3ms/step


ValueError: ignored

In [0]:
test_files = [im for im in os.listdir(TEST_DIR)]
test = np.ndarray((len(test_files), ROWS, COLS, CHANNELS), dtype=np.uint8)

for i, im in enumerate(test_files): 
    test[i] = read_image(TEST_DIR+im)
    
test_preds = model.predict(test, verbose=1)
submission = pd.DataFrame(test_preds, columns=SIGNATURE_CLASSES)
submission.insert(0, 'image', test_files)
submission.head()

submission.to_csv('/content/drive/My Drive/Signature_Recognition_DeepLearning-master/signatureResults.csv',index=False)

3/3 [==============================] - 0s 4ms/step


/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:5: DeprecationWarning: `imread` is deprecated!
`imread` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imread`` instead.
  """
/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:8: DeprecationWarning: `imresize` is deprecated!
`imresize` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``skimage.transform.resize`` instead.
  


In [0]:
#Load the pretrained Network
vgg16_model = VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=(ROWS,COLS,CHANNELS), pooling=None, classes=1000)
print("pretrained Network is loaded")

pretrained Network is loaded


In [0]:
vgg16_model.summary()

Model: "vgg16"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_3 (InputLayer)         (None, 224, 224, 3)       0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [0]:
# Freeze the layers
for layer in vgg16_model.layers:
    layer.trainable = False
print("Pretrained layers are freezed")

Pretrained layers are freezed


In [0]:
model = Sequential()
model.add(vgg16_model)
#add fully connected layer:
input_layer=model.add(Flatten())
hidden_layer=model.add(Dense(128, activation='relu', name='hidden_layer'))
classification_layer=model.add(Dense(64, activation='relu', name='classification_layer'))
output_layer=model.add(Dense(len(SIGNATURE_CLASSES), activation='softmax', name='output_layer')) 
print("All layers top of pretrained layers are developed")

All layers top of pretrained layers are developed


In [0]:
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
print("Model is Complied")

Model is Complied


In [0]:
checkpoint = ModelCheckpoint(filepath = '/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/train/weights-improvement-{epoch:02d}-{val_accuracy:.2f}.hdf5', monitor='val_acc', verbose=1, save_best_only=True, mode='max')
callbacks_list = [checkpoint]

In [0]:
model.fit(X_train, y_train, batch_size=32, nb_epoch=100,
              validation_split=0.1, verbose=1, shuffle=True, callbacks=callbacks_list)

Train on 558 samples, validate on 62 samples
Epoch 1/100
558/558 [==============================] - 2s 3ms/step - loss: 5.1910 - accuracy: 0.2204 - val_loss: 2.4089 - val_accuracy: 0.4516
Epoch 2/100
558/558 [==============================] - 2s 3ms/step - loss: 1.4565 - accuracy: 0.6326 - val_loss: 1.0978 - val_accuracy: 0.7581
Epoch 3/100
558/558 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.8530 - val_loss: 0.5127 - val_accuracy: 0.8226
Epoch 4/100
558/558 [==============================] - 2s 3ms/step - loss: 0.2477 - accuracy: 0.9229 - val_loss: 0.3166 - val_accuracy: 0.9194
Epoch 5/100
558/558 [==============================] - 2s 3ms/step - loss: 0.0451 - accuracy: 0.9857 - val_loss: 0.3818 - val_accuracy: 0.9032
Epoch 6/100
558/558 [==============================] - 2s 3ms/step - loss: 0.0154 - accuracy: 0.9982 - val_loss: 0.3221 - val_accuracy: 0.9194
Epoch 7/100
558/558 [==============================] - 2s 3ms/step - loss: 0.0044 - accuracy: 1.0

In [0]:
preds = model.predict(X_valid, verbose=1)
print("Validation Log Loss: {}".format(log_loss(y_valid, preds)))

267/267 [==============================] - 1s 4ms/step
Validation Log Loss: 0.588380526270492


In [0]:
test_files = [im for im in os.listdir(TEST_DIR)]
test = np.ndarray((len(test_files), ROWS, COLS, CHANNELS), dtype=np.uint8)

for i, im in enumerate(test_files): 
    test[i] = read_image(TEST_DIR+im)
    
test_preds = model.predict(test, verbose=1)
submission = pd.DataFrame(test_preds, columns=SIGNATURE_CLASSES)
submission.insert(0, 'image', test_files)
submission.head()

submission.to_csv('/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/signatureResults.csv',index=False)

12/12 [==============================] - 0s 3ms/step


In [0]:
# save model and architecture to single file
model.save('/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/signatureRecognition_VGG16_model.h5')
model.summary()

print("Saved model to disk")

Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 7, 7, 512)         14714688  
_________________________________________________________________
flatten_6 (Flatten)          (None, 25088)             0         
_________________________________________________________________
hidden_layer (Dense)         (None, 128)               3211392   
_________________________________________________________________
classification_layer (Dense) (None, 64)                8256      
_________________________________________________________________
output_layer (Dense)         (None, 64)                4160      
Total params: 17,938,496
Trainable params: 3,223,808
Non-trainable params: 14,714,688
_________________________________________________________________
Saved model to disk


In [0]:
# Loading saved model from Drive.
from keras.models import load_model
model = load_model('/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/signatureRecognition_VGG16_model.h5')
print("Model is Loaded")
model.summary()

Model is Loaded
Model: "sequential_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 7, 7, 512)         14714688  
_________________________________________________________________
flatten_6 (Flatten)          (None, 25088)             0         
_________________________________________________________________
hidden_layer (Dense)         (None, 128)               3211392   
_________________________________________________________________
classification_layer (Dense) (None, 64)                8256      
_________________________________________________________________
output_layer (Dense)         (None, 64)                4160      
Total params: 17,938,496
Trainable params: 3,223,808
Non-trainable params: 14,714,688
_________________________________________________________________


In [0]:
from keras.preprocessing import image
from keras.applications.vgg16 import preprocess_input
from keras.models import Model
import numpy as np
from keras.models import load_model
import ipywidgets as widgets
from IPython.display import display
button = widgets.Button(description="Click to know Name " )
output = widgets.Output()

model = load_model('/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/signatureRecognition_VGG16_model.h5')
img_path = '/content/drive/My Drive/Dataset2/sign_data.zip (Unzipped Files)/sign_data/11_052.png'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

block4_pool_features = model.predict(x)
print(block4_pool_features)
label_index=block4_pool_features.argmax()
print(label_index)
def on_button_clicked(b):
  # Display the message within the output widget.
  with output:
    print("Signature is of  "  +SIGNATURE_CLASSES[label_index])

button.on_click(on_button_clicked)
display(button, output)

[[1.07392574e-10 2.33686183e-15 1.57053474e-16 3.63359703e-07
  2.06278397e-12 5.14659648e-10 5.26925413e-11 1.13121491e-10
  1.23408617e-09 1.19378711e-07 1.47738384e-11 7.59146468e-10
  1.12326743e-08 1.42529743e-07 1.41109938e-14 2.81836261e-08
  1.50759927e-09 1.66780492e-10 1.15319144e-05 1.17536871e-07
  1.68616805e-06 4.35485390e-06 1.82785828e-10 6.03519226e-08
  2.88963997e-06 2.22058858e-07 1.76758001e-11 3.87884948e-14
  1.33578495e-11 8.05362808e-12 1.53551737e-05 4.03263585e-17
  1.60578281e-06 3.29200274e-12 6.05249878e-11 7.52718188e-06
  2.23652208e-07 2.73917353e-16 1.03515517e-13 6.31267824e-12
  2.15225684e-10 5.15619649e-06 1.58937974e-10 6.50012975e-13
  1.65133188e-05 1.07744859e-06 9.99741256e-01 3.34272526e-10
  2.03904551e-06 1.76026403e-13 4.70588737e-13 1.54898361e-09
  1.12556258e-15 3.14181463e-08 1.81714000e-04 1.67796188e-09
  8.04147200e-12 1.23990727e-12 3.76783369e-08 7.23589721e-07
  1.44527593e-11 2.06035700e-09 3.21946949e-08 5.13825989e-06]]
46


Button(description='Click to know Name ', style=ButtonStyle())

Output()

In [0]:
# image data generation
train_data_dir ='/content/drive/My Drive/Signature_Recognition_DeepLearning-master/data/train/'
val_data_dir ='/content/drive/My Drive/Signature_Recognition_DeepLearning-master/data/test/'
from keras.preprocessing.image import ImageDataGenerator
img_width, img_height = 32, 32
train_datagen = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_data_dir, target_size=(img_width, img_height), 
                                                    batch_size=47,shuffle=True, class_mode='categorical')
validation_generator = test_datagen.flow_from_directory(val_data_dir, target_size=(img_width, img_height), 
                                                    batch_size=47,shuffle=True,class_mode='categorical')

Found 47 images belonging to 12 classes.
Found 0 images belonging to 0 classes.


In [0]:
# Training Label feature identification(y_train)
 import numpy as np
 batch_size=47
 sample_count=47
 features = np.zeros(shape=(47, 64))  # Must be equal to the output of the convolutional base
 labels = np.zeros(shape=(47, 12))
 i = 0
 for inputs_batch, labels_batch in train_generator:
   features_batch = model.predict(inputs_batch)
   features[i * batch_size: (i + 1) * batch_size] = features_batch
   labels[i * batch_size: (i + 1) * batch_size] = labels_batch
   i += 1
   if i*batch_size  >= sample_count:
     break
 print(labels.shape)
 print(features.shape)

(47, 12)
(47, 64)


In [0]:
print(labels)

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.