<a href="https://colab.research.google.com/github/deepakmoud/Signature-Verification/blob/master/signature_verification_vggnet.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# Importing the Keras libraries and packages
from keras.layers import Input, Flatten, Dense
from keras.models import Sequential
from keras.layers import Convolution2D
from keras.layers import MaxPooling2D
from keras.preprocessing import image
import numpy as np
import pandas as pd
from keras.preprocessing.image import ImageDataGenerator
from keras.models import Model
from keras.layers import Input, Flatten, Dense
from keras.callbacks import Callback, ModelCheckpoint
from keras.applications.vgg16 import VGG16
from keras.applications.vgg16 import preprocess_input
import warnings 
warnings.filterwarnings('ignore')
img_width, img_height = 128, 128



Using TensorFlow backend.


In [0]:
#Load the pretrained Network
vgg16_model = VGG16(include_top=False, weights='imagenet', input_tensor=None, input_shape=(img_height,img_width,3), pooling=None, classes=1000)
print("pretrained Network is loaded")

58892288/58889256 [==============================] - 1s 0us/step
pretrained Network is loaded


In [1]:
pip install -U keras

Requirement already up-to-date: keras in /usr/local/lib/python3.6/dist-packages (2.3.1)


In [0]:
# Freeze the layers
for layer in vgg16_model.layers:
    layer.trainable = False
print("Pretrained layers are freezed")
    

Pretrained layers are freezed


In [0]:
model = Sequential()
model.add(vgg16_model)
#add fully connected layer:
input_layer=model.add(Flatten())
hidden_layer=model.add(Dense(128, activation='relu', name='hidden_layer'))
classification_layer=model.add(Dense(64, activation='relu', name='classification_layer'))
output_layer=model.add(Dense(1, activation='sigmoid', name='output_layer')) 
print("All layers top of pretrained layers are developed")

All layers top of pretrained layers are developed


In [0]:
train_data_dir ='/content/drive/My Drive/Dataset1/training_set'
val_data_dir ='/content/drive/My Drive/Dataset1/testing_set'
model_weights_file = 'vgg16-xfer-weights.h5'
nb_train_samples = 2117
nb_val_samples = 563
nb_epochs = 35
print("Input parameters are assigned")

Input parameters are assigned


In [0]:
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
print("Model is Complied")

Model is Complied


In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [0]:
train_datagen = ImageDataGenerator(rescale=1./255, shear_range=0.2, zoom_range=0.2, horizontal_flip=True)
test_datagen = ImageDataGenerator(rescale=1./255)

train_generator = train_datagen.flow_from_directory(train_data_dir, target_size=(img_width, img_height), 
                                                    batch_size=32,shuffle=False, class_mode='binary')
validation_generator = test_datagen.flow_from_directory(val_data_dir, target_size=(img_width, img_height), 
                                                    batch_size=32,shuffle=False,class_mode='binary')


Found 2117 images belonging to 2 classes.
Found 563 images belonging to 2 classes.


In [0]:
import os
from os import listdir
from numpy import asarray
from numpy import save
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
folder = '/content/drive/My Drive/Dataset1/training_set/'
photos, labels = list(), list()
for r, d, f in os.walk(folder):
    for file in f:
        if ".png" in file:
          if(os.path.join(r, file)=='/content/drive/My Drive/Dataset1/training_set/genuine/{}'.format(file)):
            output=1
          elif(os.path.join(r, file)=='/content/drive/My Drive/Dataset1/training_set/forged/{}'.format(file)):
            output=0
        labels.append(output)
labels_train=np.array(labels)
print(os.path.join(r, file))
print(labels_train.shape)
labels_train=np.expand_dims(labels, axis=1)
print(labels_train)
print(labels_train.shape)

/content/drive/My Drive/Dataset1/training_set/genuine/006_01.PNG
(2117,)
[[0]
 [0]
 [0]
 ...
 [1]
 [1]
 [1]]
(2117, 1)


In [0]:
import os
from os import listdir
from numpy import asarray
from numpy import save
from keras.preprocessing.image import load_img
from keras.preprocessing.image import img_to_array
folder = '/content/drive/My Drive/Dataset1/testing_set/'
photos, labels = list(), list()
for r, d, f in os.walk(folder):
    for file in f:
        if ".png" in file:
          if(os.path.join(r, file)=='/content/drive/My Drive/Dataset1/testing_set/genuine/{}'.format(file)):
            output=1
          elif(os.path.join(r, file)=='/content/drive/My Drive/Dataset1/testing_set/forged/{}'.format(file)):
            output=0
        labels.append(output)
labels_test=np.array(labels)
print(os.path.join(r, file))
print(labels_test.shape)
labels_test=np.expand_dims(labels_test, axis=1)
print(labels_test)
print(labels_test.shape)

/content/drive/My Drive/Dataset1/testing_set/genuine/NFI-03001030.PNG
(563,)
[[1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1

In [0]:
callbacks = [ModelCheckpoint(model_weights_file, monitor='val_acc', save_best_only=True)]

history = model.fit_generator( train_generator, callbacks = callbacks, nb_epoch=nb_epochs, validation_data=validation_generator)

print('Training Completed!')


Epoch 1/35


KeyboardInterrupt: ignored

In [0]:
 # save model and architecture to single file
model.save("model_vggnet_signature_verification.h5")
model.summary()

print("Saved model to disk")

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
vgg16 (Model)                (None, 4, 4, 512)         14714688  
_________________________________________________________________
flatten_1 (Flatten)          (None, 8192)              0         
_________________________________________________________________
hidden_layer (Dense)         (None, 128)               1048704   
_________________________________________________________________
classification_layer (Dense) (None, 64)                8256      
_________________________________________________________________
output_layer (Dense)         (None, 1)                 65        
Total params: 15,771,713
Trainable params: 1,057,025
Non-trainable params: 14,714,688
_________________________________________________________________
Saved model to disk


In [0]:
from keras.models import load_model
layer_name= 'classification_layer'
model = load_model('model_vggnet_signature_verification.h5')
intermediate_layer_model = Model(inputs=model.input,
                                 outputs=model.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model.predict(train_generator)



Using TensorFlow backend.


OSError: ignored

In [0]:
label_testmodel=model.predict(validation_generator)
label_testmodel = np.array(label_testmodel)
print(label_testmodel.shape)

(563, 1)


In [0]:
img_path = '/content/drive/My Drive/Dataset1/training_set/genuine/NFI-00102001.png'
label = ['Genuine','Forged']
img = image.load_img(img_path, target_size=(128,128))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
print(x.shape)
features = model.predict(x)
print(features)
print(features[0][0])
  
if features[0]>0.5:
    print(" is  Genuine")
else:
    print(" is Forged")
    

(1, 128, 128, 3)
[[1.8042749e-05]]
1.8042749e-05
 is Forged


In [0]:

from keras.applications.vgg16 import preprocess_input
vgg16_feature_train = intermediate_layer_model.predict(train_generator)
# print(vgg16_feature)
vgg16_feature_np_train = np.array(vgg16_feature_train)
print(vgg16_feature_np_train)
print(vgg16_feature_np_train.shape)

vgg16_feature_test = intermediate_layer_model.predict(validation_generator)
# print(vgg16_feature)
vgg16_feature_np_test = np.array(vgg16_feature_test)
print(vgg16_feature_np_test)
print(vgg16_feature_np_test.shape)


        


[[0.33078888 0.2582102  1.161821   ... 0.24485923 0.         0.        ]
 [0.66878617 0.03646358 1.4288685  ... 0.12246179 0.         0.        ]
 [0.7096568  0.20445617 1.2668296  ... 0.12272289 0.         0.        ]
 ...
 [0.83315754 0.07563186 1.7555441  ... 0.44245476 0.29632604 0.        ]
 [0.88018775 0.         1.3992904  ... 0.41136461 0.30021462 0.        ]
 [0.77838993 0.19151579 1.5586798  ... 0.5683359  0.15793484 0.        ]]
(2117, 64)
[[1.1888729  0.21398574 1.4905199  ... 0.07391414 0.14307915 0.        ]
 [0.86647946 0.09610424 1.0843405  ... 0.         0.         0.        ]
 [0.5563555  0.2632261  1.4372698  ... 0.44435868 0.         0.        ]
 ...
 [0.46801585 0.02981245 1.4219254  ... 0.31891996 0.17926161 0.        ]
 [0.69586885 0.04371358 1.503937   ... 0.35886517 0.3962226  0.        ]
 [0.78598243 0.01214612 1.425491   ... 0.18263072 0.290466   0.        ]]
(563, 64)


In [0]:
import h5py
hf = h5py.File('model_vggnet_signature_verification.h5', 'w')
hf.create_dataset('dataset_1', data=x)

hf.close()

In [0]:
pred=intermediate_layer_model.predict_generator(train_generator,
steps=nb_train_samples/ nb_epochs, verbose=1)

61/60 [==============================] - 333s 5s/step


In [0]:
print(pred)
print(pred.size)

[[0.3980213  0.30647075 0.40905815 ... 0.01521254 0.         0.        ]
 [1.0422325  0.3940553  0.5411707  ... 0.         0.28103122 0.        ]
 [0.9323369  0.58008325 0.418647   ... 0.         0.         0.        ]
 ...
 [0.51847756 0.16396233 0.         ... 0.         0.         0.        ]
 [0.7589096  0.37691092 0.27034187 ... 0.         0.08792037 0.        ]
 [0.7406855  0.5252509  0.27055356 ... 0.         0.14309968 0.        ]]
249856


In [0]:

print(pred.shape)


(1952, 128)


In [0]:
# Evaluate the model on the test data using `evaluate`
print('\n# Evaluate on test data')
results = model.evaluate(validation_generator)
print('test loss, test acc:', results)


# Evaluate on test data
18/18 [==============================] - 98s 5s/step
test loss, test acc: [0.7307572364807129, 0.481349915266037]


In [0]:
# SVM
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'linear', random_state = 0)
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))



[[ 19  13]
 [230 301]]
0.5683836589698046


In [0]:
# Kernel SVM
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.svm import SVC
classifier = SVC(kernel = 'rbf', random_state = 0)
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))




[[ 18  14]
 [239 292]]
0.5506216696269982


In [0]:
# Random Forest
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 10, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))

[[ 20  12]
 [273 258]]
0.4937833037300178


In [0]:


# Decision Tree
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier(criterion = 'entropy', random_state = 0)
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))

[[ 19  13]
 [234 297]]
0.5612788632326821


In [0]:
# Naive Bayes
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))

[[  1  31]
 [  5 526]]
0.9360568383658969


In [0]:
# K Nearest Neighbor
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.neighbors import KNeighborsClassifier
classifier =  KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))

[[ 13  19]
 [182 349]]
0.6429840142095915


In [0]:
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)



In [0]:
# Logistic Classification
# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(vgg16_feature_np_train)
X_test = sc.transform(vgg16_feature_np_test)

# Fitting SVM to the Training set
from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression(random_state = 0)

classifier.fit(X_train, labels_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(labels_test, y_pred)
print(cm)
from sklearn.metrics import accuracy_score
print(accuracy_score(labels_test, y_pred))

[[ 20  12]
 [244 287]]
0.5452930728241563
